### ISSUE TITLE
Allow for custom pin declarations?

### ISSUE THREAD

**Issue by Greyoxide** [jobitjoseph/fbcp-ST7796#2]
It looks like this project uses hard coded pin definitions. The issue I'm facing is that the required pins are already occupied. I'm wondering if it would be possible to define custom pins via make flags?

Perhaps something like this:

`cmake -DSPI_BUS_CLOCK_DIVISOR=6 \
      -DGPIO_TFT_DATA_CONTROL=12 \
      -DGPIO_TFT_RESET_PIN=13 \
      -DGPIO_TFT_BACKLIGHT=1 \
      -DSPI_MISO_PIN=7 \
      -DSPI_MOSI_PIN=6 \
      -DSPI_SCLK_PIN=5 \
      -DSPI_CS_PIN=19 \
      -DST7796S=ON \
      -DDMA_TX_CHANNEL=7 \
      -DDMA_RX_CHANNEL=6 ..`

**Comment by jobitjoseph** [comment]
You can use the make flags to change the DC and Reset pins. Since alternate pin functions for the Raspberry pi are fixed , it is not possible to change the SPI pins. Since Closing this issue .
